version: "3.8"

services:
  web:
    container_name: kangooroad-web
    image: 168.231.87.179:1112/kangooroad/kangooroad_web:latest
    # build:
    #  context: ./frontend
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - api
    networks:
      - kangooroad-network
  api:
    container_name: kangooroad-api
    image: 168.231.87.179:1112/kangooroad/kangooroad_api:latest
    # build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - kangooroad-network
  db:
    container_name: kangooroad-db
    image: postgres:17
    restart: always
    ports:
      - "4433:4432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - kangooroad-network
volumes:
  postgres_data:

networks:
  kangooroad-network:
    driver: bridge