version: "3.8"

services:
  web:
    container_name: kangooroad-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - kangooroad-network
  api:
    container_name: kangooroad-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - kangooroad-network
  db:
    container_name: kangooroad-db
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - kangooroad-network
volumes:
  postgres_data:

networks:
  kangooroad-network:
    external: true